nome = input("Digite o seu nome completo: ")
print("Seu nome em maiusculo {}".format(nome.upper()))
print("Seu nome em minusculo {}".format(nome.lower()))
print("Seu nome tem ao todo {} letras".format(len(nome.strip())))
dividido = nome.split()
print("Seu primeiro nome e {}, e tem {} letras".format(dividido[0], len(dividido[0])))
